### ISSUE TITLE
Tracking updates to documentation for tables api

### ISSUE THREAD

**Issue by ashander** [jeromekelleher/msprime#323]
below done in #334 
- [x] NodeTable and EdgeTable documentation (some done in #321)
- [x] tables I/O (eg `load_tables` , `dump_tables`) 
- [x] tables manipulation (eg `simplify_tables`) --- #287
-  [x] define sort order (done in #321)

still todo
- [x] update error messages https://github.com/jeromekelleher/msprime/issues/280
- [x] add requirements related to mutations (see https://github.com/jeromekelleher/msprime/issues/291 )

 (feel free to add suggestions below)

**Comment by ashander** [comment]
also
-  [x] define sort order (done in #321)
- [ ] update error messages https://github.com/jeromekelleher/msprime/issues/280

**Comment by ashander** [comment]
and

- [ ] add requirements related to mutations (see https://github.com/jeromekelleher/msprime/issues/291 )
